parameters:
    sulu.preview.voter_class: 'Sulu\Bundle\PreviewBundle\Security\PreviewVoter'

framework:
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

services:
    sulu.preview.voter:
        class: '%sulu.preview.voter_class%'
        public: false
        tags:
            - { name: security.voter }
